// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAnjEkV-MW0xeNHezWtqMEn8DjDKmgX8kQ',
    appId: '1:25094778776:web:10ce2af5e37721ddb9c5ed',
    messagingSenderId: '25094778776',
    projectId: 'ton-217b6',
    authDomain: 'ton-217b6.firebaseapp.com',
    storageBucket: 'ton-217b6.appspot.com',
    measurementId: 'G-2R9TGYNX0G',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDIThn70okle2AUbUD5Z7yVnslburfI8bA',
    appId: '1:25094778776:android:f36a5502f042aa7bb9c5ed',
    messagingSenderId: '25094778776',
    projectId: 'ton-217b6',
    storageBucket: 'ton-217b6.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAKi9cRBoGL5MFgQNESdjRXvO9gb-nRSxc',
    appId: '1:25094778776:ios:66ae52f78285ffd6b9c5ed',
    messagingSenderId: '25094778776',
    projectId: 'ton-217b6',
    storageBucket: 'ton-217b6.appspot.com',
    iosBundleId: 'com.example.workoutApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAKi9cRBoGL5MFgQNESdjRXvO9gb-nRSxc',
    appId: '1:25094778776:ios:77222792893b16fab9c5ed',
    messagingSenderId: '25094778776',
    projectId: 'ton-217b6',
    storageBucket: 'ton-217b6.appspot.com',
    iosBundleId: 'com.example.workoutApp.RunnerTests',
  );
}
